-- import.sql
INSERT INTO artilharia(id, ano, nome, gols) VALUES (1, 1912, 'Arnaldo', 16);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (2, 1913, 'Gumercindo', 9);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (3, 1914, 'Riemer', 14);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (4, 1915, 'Riemer', 18);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (5, 1916, 'Riemer', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (6, 1917, 'Juarez', 14);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (7, 1918, 'Geraldo', 10);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (8 ,1919, 'Sidney Pullen', 12);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (9 ,1920, 'Junqueira', 17);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (10 ,1921, 'Nonô', 14);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (11 ,1922, 'Nonô', 9);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (12 ,1923, 'Nonô', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (13 ,1924, 'Nonô', 19);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (14 ,1925, 'Nonô', 30);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (15 ,1926, 'Fragoso', 23);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (16 ,1927, 'Fragoso', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (17 ,1928, 'Angenor', 16);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (18 ,1929, 'Fragoso', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (19 ,1930, 'Vicentino', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (20 ,1931, 'Rolinha', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (21 ,1932, 'Nelson', 27);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (22 ,1933, 'Nelson', 16);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (23 ,1934, 'Alfredinho', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (24 ,1935, 'Alfredinho', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (25 ,1936, 'Alfredinho', 45);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (26 ,1937, 'Leônidas da Silva', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (27 ,1938, 'Leônidas da Silva', 35);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (28 ,1939, 'Leônidas da Silva', 19);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (29 ,1940, 'Leônidas da Silva', 44);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (30 ,1941, 'Pirillo', 41);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (31 ,1942, 'Pirillo', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (32 ,1943, 'Pirillo', 27);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (33 ,1944, 'Pirillo', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (34 ,1945, 'Pirillo', 32);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (35 ,1946, 'Perácio', 32);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (36 ,1947, 'Pirillo', 33);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (37 ,1948, 'Jair Rosa PINTO', 29);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (38 ,1949, 'Durval', 42);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (39 ,1950, 'Durval', 44);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (40 ,1951, 'Hermes', 39);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (41 ,1952, 'Benítez', 27);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (42 ,1953, 'Índio', 41);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (43 ,1954, 'Benítez', 24);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (44 ,1955, 'Evaristo de Macedo', 35);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (45 ,1956, 'Índio', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (46 ,1957, 'Henrique Frade', 46);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (47 ,1958, 'Dida', 33);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (48 ,1959, 'Dida', 46);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (49 ,1960, 'Gérson', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (50 ,1961, 'Henrique Frade', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (51 ,1962, 'Dida', 43);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (52 ,1963, 'Aírton Beleza', 26);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (53 ,1964, 'Aírton Beleza', 40);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (54 ,1965, 'Silva Batuta', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (55 ,1966, 'Silva Batuta', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (56 ,1967, 'Ademar', 32);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (57 ,1968, 'Silva Batuta', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (58 ,1969, 'Dionísio', 30);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (59 ,1970, 'Fio Maravilha', 20);