-- import.sql
INSERT INTO artilharia(id, ano, nome, gols) VALUES (1 , 1912, 'Arnaldo', 16);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (2 , 1913, 'Gumercindo', 9);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (3 , 1914, 'Riemer', 14);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (4 , 1915, 'Riemer', 18);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (5 , 1916, 'Riemer', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (6 , 1917, 'Juarez', 14);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (7 , 1918, 'Geraldo', 10);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (8 , 1919, 'Sidney Pullen', 12);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (9 , 1920, 'Junqueira', 17);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (10 , 1921, 'Nonô', 14);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (11 , 1922, 'Nonô', 9);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (12 , 1923, 'Nonô', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (13 , 1924, 'Nonô', 19);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (14 , 1925, 'Nonô', 30);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (15 , 1926, 'Fragoso', 23);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (16 , 1927, 'Fragoso', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (17 , 1928, 'Angenor', 16);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (18 , 1929, 'Fragoso', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (19 , 1930, 'Vicentino', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (20 , 1931, 'Rolinha', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (21 , 1932, 'Nelson', 27);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (22 , 1933, 'Nelson', 16);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (23 , 1934, 'Alfredinho', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (24 , 1935, 'Alfredinho', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (25 , 1936, 'Alfredinho', 45);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (26 , 1937, 'Leônidas da Silva', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (27 , 1938, 'Leônidas da Silva', 35);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (28 , 1939, 'Leônidas da Silva', 19);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (29 , 1940, 'Leônidas da Silva', 44);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (30 , 1941, 'Pirillo', 41);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (31 , 1942, 'Pirillo', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (32 , 1943, 'Pirillo', 27);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (33 , 1944, 'Pirillo', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (34 , 1945, 'Pirillo', 32);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (35 , 1946, 'Perácio', 32);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (36 , 1947, 'Pirillo', 33);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (37 , 1948, 'Jair Rosa PINTO', 29);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (38 , 1949, 'Durval', 42);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (39 , 1950, 'Durval', 44);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (40 , 1951, 'Hermes', 39);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (41 , 1952, 'Benítez', 27);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (42 , 1953, 'Índio', 41);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (43 , 1954, 'Benítez', 24);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (44 , 1955, 'Evaristo de Macedo', 35);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (45 , 1956, 'Índio', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (46 , 1957, 'Henrique Frade', 46);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (47 , 1958, 'Dida', 33);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (48 , 1959, 'Dida', 46);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (49 , 1960, 'Gérson', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (50 , 1961, 'Henrique Frade', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (51 , 1962, 'Dida', 43);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (52 , 1963, 'Aírton Beleza', 26);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (53 , 1964, 'Aírton Beleza', 40);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (54 , 1965, 'Silva Batuta', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (55 , 1966, 'Silva Batuta', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (56 , 1967, 'Ademar', 32);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (57 , 1968, 'Silva Batuta', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (58 , 1969, 'Dionísio', 30);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (59 , 1970, 'Fio Maravilha', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (60 , 1971, 'Fio Maravilha', 12);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (61 , 1972, 'Caio Cambalhota', 25);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (62 , 1973, 'Dadá Maravilha', 22);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (63 , 1974, 'Zico', 49);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (64 , 1975, 'Zico', 51);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (65 , 1976, 'Zico', 56);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (66 , 1977, 'Zico', 39);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (67 , 1978, 'Zico', 26);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (68 , 1979, 'Zico', 81);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (69 , 1980, 'Zico', 47);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (70 , 1981, 'Nunes', 48);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (71 , 1982, 'Zico', 48);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (72 , 1983, 'Baltazar', 23);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (73 , 1984, 'Tita', 22);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (74 , 1985, 'Bebeto', 26);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (75 , 1986, 'Bebeto', 31);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (76 , 1987, 'Bebeto', 15);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (77 , 1988, 'Bebeto', 34);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (78 , 1989, 'Zinho', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (79 , 1990, 'Gaúcho', 38);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (80 , 1991, 'Gaúcho', 35);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (81 , 1992, 'Júnior', 16);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (82 , 1993, 'Nílson', 25);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (83 , 1994, 'Charles Baiano', 18);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (84 , 1995, 'Romário', 44);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (85 , 1996, 'Romário', 37);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (86 , 1997, 'Romário', 35);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (87 , 1998, 'Romário', 40);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (88 , 1999, 'Romário',	48);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (89 , 2000, 'Petković', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (90 , 2001, 'Edílson', 28);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (91 , 2002, 'Liedson', 15);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (92 , 2003, 'Edílson', 16);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (93 , 2004, 'Jean', 15);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (94 , 2005, 'Renato Abreu', 14);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (95 , 2006, 'Renato Abreu', 19);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (96 , 2007, 'Souza', 15);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (97 , 2008, 'Marcinho', 17);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (98 , 2009, 'Adriano',	19);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (99 , 2010, 'Vágner Love', 23);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (100 , 2011, 'Deivid', 21);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (101 , 2011, 'Ronaldinho Gaúcho', 21);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (102 , 2011, 'Thiago Neves', 21);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (103 , 2012, 'Vágner Love', 24);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (104 , 2013, 'Hernane', 36);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (105 , 2014, 'Alecsandro', 21);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (106 , 2015, 'Alecsandro', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (107 , 2015, 'Marcelo Cirino', 11);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (108 , 2016, 'Paolo Guerrero', 18);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (109 , 2017, 'Paolo Guerrero', 20);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (110 , 2018, 'Henrique Dourado', 12);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (111 , 2018, 'Lucas Paquetá', 12);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (112 , 2019, 'Gabriel Barbosa', 43);
INSERT INTO artilharia(id, ano, nome, gols) VALUES (113 , 2020, 'Gabriel Barbosa', 11);